os:
  - linux
  - osx

script:
  - git submodule update --init --recursive
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) <<< $'\ny\ny'
  - opam init
  - make install_deps
  - make run
