language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.09

script:
  - git submodule update --init --recursive
  - bash -ex .travis-opam.sh
  - sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh) <<< $'\ny\ny'
  - opam init
  - make install_deps
  - make run
